#!/bin/sh



cd ~/.config/wallpapers/
[ -z $1 ] && \
ls ~/.config/wallpapers | \
dmenu -l 5 -i -nb '#282828' -nf '#ebdbb2' -sb '#ebdbb2' -sf '#1f222d' -fn 'Roboto:bold:pixelsize=14'| \
xargs nitrogen --set-zoom-fill --random \
|| nitrogen --set-zoom-fill $1
 
