#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc rule -a kitty state=floating border=off
bspc rule -a Zathura state=tiled 
bspc rule -a mpv follow=on

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9


#borders and colors
bspc config normal_border_color "#262626"
bspc config focused_border_color "#4E3524"
bspc config border_width	10
bspc config window_gap		3
bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	true


#to switch caps with escape
setxkbmap -option "caps:escape" 


: '
Uncomment the following line to make the Caps Lock button
work as Escape when pressed alone, and as Ctrl when pressed 
with another key.
'
#xcape -e 'Caps_Lock=Escape'
#setxkbmap -option "caps:ctrl_modifier"


#increase cursor speed
xset r rate 300 50

#disable screen blackening
xset s off && xset -dpms

#hide mouse cursor if it is inactive 
unclutter &

#turns touchpad off
synclient TouchpadOff=1

#turn keyboard layout to United States
setxkbmap us

xgamma -gamma 0.8
picom &

