#!/bin/sh

# Gruvbox themed bspwm config 

[ -z $XDG_COLOR_TRANSFORM ] && XDG_COLOR_TRANSFORM="#4E3524"
[ -z $XDG_COLOR_INACTIVE_TRANSFORM ] && XDG_COLOR_INACTIVE_TRANSFORM="#262626"

pgrep -x sxhkd > /dev/null || sxhkd &


bspc rule -a kitty state=floating border=off
bspc rule -a Zathura state=tiled 
bspc rule -a mpv follow=on

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9


#borders and colors
bspc config normal_border_color $XDG_COLOR_INACTIVE_TRANSFORM
bspc config focused_border_color $XDG_COLOR_TRANSFORM
bspc config border_width	10
bspc config window_gap		3
bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	true


# setxkbmap -option "caps:escape"  #to switch caps with escape


# Uncomment the following 2 lines to make the Caps Lock button
# work as Escape when pressed alone, and as Ctrl when pressed 
# with another key.

# xcape -e 'Caps_Lock=Escape' 
setxkbmap -option "caps:ctrl_modifier"

xset r rate 300 50   		#increase cursor speed
xset s off && xset -dpms	#disable screen blackening
unclutter & 			#hide mouse cursor if it is inactive 
setxkbmap us 			#turn keyboard layout to United States
xgamma -gamma 0.8
picom &
